### ISSUE TITLE
Oric Atmos: RAM stated too low (must be 48k or 64k, not 16k)

### ISSUE THREAD

**Issue by xahmol** [MarquisdeGeek/20-GOTO-10#1]
RAM for the Oric Atmos is now stated as 16384 in https://github.com/MarquisdeGeek/20-GOTO-10/blob/main/MachineList/oric/atmos.json

However the Oric Atmos is sold as 48k RAM computer, and actually has 64K of RAM (16 of which is not easily accessible though).
See https://osdk.org/index.php?page=articles&ref=ART14

Did not do a pull request as I with this background am not sure if it should be 48k or 64k in the JSON, leave it up to you to be also consistent with the other entries here. But 16k is clearly incorrect.

**Comment by MarquisdeGeek** [comment]
Fixed, with notes. My logic is that since the RAM can't be accessed it's RM, and therefore not counted!

**Comment by xahmol** [comment]
Agree, thought so, exactly the reason why I did not do the entry directly.
